### ISSUE TITLE
Mapping view model for sections with NSFetchedResultsController

### ISSUE THREAD

**Issue by lazlox** [DenTelezhkin/DTTableViewManager#66]
Hi there, how can one set the view model mapping for section headers when using NSFetchedResultsController?
Getting this in console:

> [DTTableViewManager] UITableView requested a header/footer view for model ar [6], but view model mapping for it was not found

My code so far:
```
        manager.tableViewUpdater = manager.coreDataUpdater()
        manager.storage = CoreDataStorage(fetchedResultsController: fetchedResultsController)
        manager.registerHeader(AgendaSectionHeaderCell.self)
```

**Comment by DenTelezhkin** [comment]
Hi!

In 6.x version supplementaries for CoreDataStorage are selected from `NSFetchedResultsSectionInfo.name`, you can see how they are selected in code here:

https://github.com/DenTelezhkin/DTModelStorage/blob/7.4.1/Sources/DTModelStorage/CoreDataStorage.swift#L102-L113

Basically this means that is you have a `sectionNameKeyPath` for `NSFetchedResultsController`, section name will be used as a header model for UITableView. By default it's string, so probably you need to check if AgendaSectionHeaderCell accepts String model from `ModelTransfer` protocol or something else. 

If you need different header model, you need to subclass CoreDataStorage and override method from previous link.

In 7.0.0-beta release for DTTableViewManager release yesterday, there's no need to subclass, and you can set `headerModelProvider` or `footerModelProvider` however you need.
