### ISSUE TITLE
Side effect with using coreDataUpdater()

### ISSUE THREAD

**Issue by ageevvalentin** [DenTelezhkin/DTTableViewManager#67]
Hi, I gets a strange behavior with using ```coreDataUpdate()```, whose contains ```updateCellClosure()```. It func put updated model to cell directly, but after I changed my model in the Core Data I want use another cell, but ```cellForItem``` not calls with ```updateCellClosure()```.

**Comment by DenTelezhkin** [comment]
Hi!
The reason why this specific convenience behavior has been implemented, is Apple's documentation on handling updates from NSFetchedResultsControllerDelegate(https://developer.apple.com/documentation/coredata/nsfetchedresultscontrollerdelegate)

As you can see, in their example when `NSFetchedResultsChangeUpdate ` is received, cell is updated directly. 

```
case NSFetchedResultsChangeUpdate:
            [self configureCell:[tableView cellForRowAtIndexPath:indexPath]
                  atIndexPath:indexPath];
```

This exact behavior is implemented by `coreDataUpdater` and `updateCellClosure`. However, `coreDataUpdater`and `updateCellClosure` are both a convenience methods, and you can customize any behavior by setting `TableViewUpdater.reloadRowClosure` in any way you need.
