### ISSUE TITLE
Issue with programmatically added tableView 

### ISSUE THREAD

**Issue by EngrAhsanAli** [DenTelezhkin/DTTableViewManager#73]
Hi!

I tried to wrapping _DTTableViewManager_ and providing dynamically added _UITableView_. So when added `addSubview(tableView)` the following delegate needs some time to wait for its addition.

`self.manager.startManaging(withDelegate: self)`

However, I made the workaround which works well, but of course, it's not preferable.

```
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
       self.manager.startManaging(withDelegate: self)
} 
```

Any good way to deal with programmatically added _UITableView_ in class extended from _NSObject_?

**Comment by DenTelezhkin** [comment]
Hi!

What makes you think that you need to wait some time before calling `startManaging(withDelegate:)`?

**Comment by EngrAhsanAli** [comment]
Hello!

I use to get the following error sometimes but now it's working well, closing this thread with an excuse! Thanks anyway!

_Call startManagingWithDelegate: method only when UITableView has been created_
