### ISSUE TITLE
Cannot build for simulator on M1 Mac

### ISSUE THREAD

**Issue by bstillitano** [DenTelezhkin/DTTableViewManager#77]
When trying to build for simulator devices on an M1 mac, I get the following error:
```Could not find module 'DTModelStorage' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator```

I am able to build and run on real devices as well as archive my project.

**Comment by DenTelezhkin** [comment]
Can you add more details please? What installation method are you using, what package manager/Xcode is used etc. 

I found a bunch of related issues, https://github.com/ReactiveX/RxSwift/pull/2262, https://github.com/apollographql/apollo-ios/issues/1485, but I don't see definitive solution in those. Setting `ONLY_ACTIVE_ARCH ` to NO leads to build failures in `DTModelStorage`, so it does not seem like a proper solution. 

Unfortunately, I also don't have M1 Mac, so cannot test those myself, would love some help from your side, were you able to use some other libraries/frameworks with your setup?

**Comment by DenTelezhkin** [comment]
I tested the same settings on MacOS Big Sur (Intel) and Xcode 12.5 Beta 3, and changing `ONLY_ACTIVE_ARCH` to NO did not trigger any build errors, which leads me to believe this is an Xcode issue and not something we can do to project settings, which is unfortunate.

I'm going to leave this issue open, as it seems some projects are unaffected by this build failure, but I have no idea how to fix this in `DTModelStorage` / `DTTableViewManager`, especially given the fact, that build settings are generated by SPM, and most of them cannot be changed by user. 

If you have any ideas how to work around this build failure, please let me know.
